name: 构建并推送Docker镜像

on:
  push:
    tags:
      - 'node*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: 解析标签并设置变量
      id: parse_tag
      run: |
        chmod +x ./action.sh
        ./action.sh

    - name: 登录到Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: 登录到GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 设置Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: 构建并推送
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/pack:${{ steps.parse_tag.outputs.TAG }}
          ghcr.io/${{ github.repository_owner }}/pack:${{ steps.parse_tag.outputs.TAG }}
        build-args: |
          NODE_VERSION=${{ env.NODE_VERSION }}
          BUN_VERSION=${{ env.BUN_VERSION }}
          PYTHON_VERSION=${{ env.PYTHON_VERSION }}
          NODE_BASE_IMAGE_TAG=${{ env.NODE_BASE_IMAGE_TAG }}
